---
output: rmarkdown::github_document
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r vers, message=FALSE, warning=FALSE, error=FALSE, cache=FALSE}
library(longurl)
library(magrittr)

# current version
packageVersion("longurl")
```

```{r ex1}
c(
  "http://t.co/D4C7aWYIiA",
  "1.usa.gov/1J6GNoW",
  "ift.tt/1L2Llfr",
  "bit.ly/1GPr5w5",
  "http://l.dds.ec/1da152x",
  "http://l.rud.is/seven",
  "qrp://not a valid url/"
) -> test_urls

expand_urls(test_urls) %>% 
  dplyr::select(orig_url, status_code, expanded_url) %>% 
  knitr::kable()
```

## longurl Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. By participating in this project you agree to abide by its terms.

